# Generated by Django 2.2.12 on 2020-04-08 19:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование ЗС')),
                ('type', models.CharField(choices=[('A', 'Тип А'), ('B', 'Тип Б')], max_length=128, verbose_name='Тип ЗС')),
                ('map_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Земные станции',
                'verbose_name': 'Земная станция',
            },
        ),
    ]
