# Generated by Django 2.2.12 on 2020-04-08 19:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200408_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Точки поиска',
                'verbose_name': 'Точка поиска',
            },
        ),
    ]
