# Generated by Django 2.2.12 on 2020-04-08 23:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_searchpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMultiPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('loc', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Множества точек поиска',
                'verbose_name': 'Множество точек поиска',
            },
        ),
    ]
