# Generated by Django 2.2.12 on 2020-06-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_searchmultipoligon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchmultipoligon',
            options={'verbose_name': 'Множество районов поиска', 'verbose_name_plural': 'Множества районов поиска'},
        ),
        migrations.AddField(
            model_name='satellite',
            name='mass',
            field=models.FloatField(default=1000, verbose_name='Масса спутника, кг'),
        ),
    ]
