# Generated by Django 2.2.12 on 2020-06-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200603_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decoder_antenna',
            old_name='encoder',
            new_name='decoder',
        ),
    ]
