# Generated by Django 2.2.12 on 2020-06-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200603_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoder',
            name='satellite',
        ),
        migrations.AddField(
            model_name='decoder',
            name='sat_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decoder', to='polls.SatSystem'),
        ),
    ]
