# Generated by Django 2.2.12 on 2020-06-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200604_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decoder',
            old_name='power_input',
            new_name='power_output',
        ),
    ]
