# Generated by Django 2.2.12 on 2020-06-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200604_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoder_antenna',
            name='angle_os',
        ),
        migrations.RemoveField(
            model_name='decoder_antenna',
            name='k_power',
        ),
        migrations.RemoveField(
            model_name='decoder_antenna',
            name='k_retire',
        ),
        migrations.RemoveField(
            model_name='decoder_antenna',
            name='lenth_vawe',
        ),
        migrations.RemoveField(
            model_name='decoder_antenna',
            name='name',
        ),
        migrations.RemoveField(
            model_name='decoder_antenna',
            name='type',
        ),
        migrations.AddField(
            model_name='decoder',
            name='diapazon_V',
            field=models.FloatField(default=10000000000, verbose_name='Количество каналов'),
        ),
        migrations.AlterField(
            model_name='decoder_antenna',
            name='decoder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dec_antenna', to='polls.Decoder'),
        ),
        migrations.AlterField(
            model_name='decoder_antenna',
            name='lenth_a',
            field=models.FloatField(default=0, verbose_name='Длина антенны'),
        ),
        migrations.AlterField(
            model_name='decoder_antenna',
            name='lenth_arm',
            field=models.FloatField(default=1, verbose_name='Длина плеча'),
        ),
        migrations.AlterField(
            model_name='decoder_antenna',
            name='lenth_sign_ang',
            field=models.FloatField(default=1, verbose_name='Расстояние между излучателями в угл. плоскости'),
        ),
        migrations.AlterField(
            model_name='decoder_antenna',
            name='lenth_sign_az',
            field=models.FloatField(default=1, verbose_name='Расстояние между излучателями в аз. плоскости'),
        ),
        migrations.AlterField(
            model_name='decoder_antenna',
            name='num_sign_ang',
            field=models.IntegerField(default=5, verbose_name='Количество излучателей в угл. плоскости'),
        ),
        migrations.AlterField(
            model_name='decoder_antenna',
            name='num_sign_az',
            field=models.IntegerField(default=5, verbose_name='Количество излучателей в аз. плоскости'),
        ),
        migrations.AlterField(
            model_name='decoder_antenna',
            name='width_a',
            field=models.FloatField(default=0, verbose_name='Ширина антенны'),
        ),
    ]
