# Generated by Django 2.2.12 on 2020-06-06 21:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_decoder_satellite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наназвание терминала')),
                ('map_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('power', models.IntegerField(default=100, verbose_name='Средняя излучаемая мощность')),
                ('diametr', models.FloatField(default=0, verbose_name='Диаметр антенны')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
            },
        ),
    ]
